config/routes.rb
Rails.application.routes.draw do
  root 'main#home'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :patients
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord
	belongs_to :user
	has_attached_file :cover, styles: { thumb: "100x100#" }
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/
  validates :disease, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	
	has_many :patients  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	before_action :authenticate_user!
  def home
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_patient, except: [:index, :new, :create]

  def index
  	@patients = Patient.all
  end

  def new
  	@patient = Patient.new
  end

  def create
  	@meetings = Meeting.all
  	@patient = current_user.patients.new(patient_params)
  	if @patient.save
  		redirect_to @patient
	  else
	  	render :new
	  end
  end

  def show
  end

  def edit
	end

  def update
	  if @patient.update(patient_params)
	    redirect_to @patient
	  else
	    render :edit
	  end
	end

  def destroy
  	@patient.destroy
  	redirect_to patients_path
  end

  private

  def set_patient
  	@patient = Patient.find(params[:id])
  end

  def patient_params
  	params.require(:patient).permit(:disease, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diseases_helper.rb
module DiseasesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/diseases/index.html.erb
<p>Find me in app/views/diseases/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MedicTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if user_signed_in?%>
      <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/main/home.html.erb
<h1>Hola bienvenido a tu consulta</h1>
<div>
	<%= link_to "Ingresa a este link para agregar tus síntomas", new_patient_path %>
</div>

app/views/patients/_form.html.erb
<h1><%=name %>tus síntomas</h1>
<%= form_for(@patient)  do |f| %>
	<div class="field">
		<%= f.text_field :disease, placeholder: "Enfermedad" %>
	</div>
	<div class="field">
		<%= f.text_area :body, placeholder: "Describe tus sintómas", style: "height: 250px;" %>
	</div>
	<div>
		Portada: <%= f.file_field :cover %>
	</div>

	<%= month_calendar(attribute: :starts_at) do |date| %>
	  <%= date %>
	<% end %>
	<div class="field">
		<%= f.submit "Guardar" %>
	</div>

	<!-- My calendar element -->
<div id="my-calendar"></div>
<!-- Dynamic create it -->
<script type="text/javascript">
    // Get the element
    var element = document.getElementById("my-calendar");
    // Create the calendar
    jsCalendar.new(element, "30/01/2017", {
        navigator : true,
        navigatorPosition : "left",
        zeroFill : false,
        monthFormat : "month YYYY",
        dayFormat : "DDD",
        language : "en"
    });
</script>
<% end %>

app/views/patients/edit.html.erb
<div style="width: 80%; margin: 0 auto;">	
	<%= render "form", name: "Edita tus síntomas" %>

</div>

app/views/patients/index.html.erb
<%= @patients.each do |patient| %>
	<h1><%=link_to patient.disease, patient%></h1>
	<div>
		<%= patient.body %> - <%= link_to "Eliminar", patient, method: :delete %>
	</div>
<% end %>

app/views/patients/new.html.erb
<div style="width: 80%; margin: 0 auto;">	
	<%= render "form", name: "Agrega tus síntomas" %>
</div>

app/views/patients/show.html.erb
<h1>Estás son tus enfermedades</h1>
<div>
	<h3><%= @patient.disease%></h3>
	<p><%= link_to "Editar", edit_patient_path %></p>
	<p><%= link_to "Regresar", patients_path %></p>
</div>